version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
      - apt-get install -y wget
    finally:
      - echo This always runs even if the update or install command fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn clean package
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - echo See the current directory content
      - pwd
      - echo $HOME
      - ls -la
      - mvn clean verify -Denvironment=local -Dwebdrive.file.location=./chromedriver
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
  discard-paths: yes
  secondary-artifacts:
    artifact1:
      files:
        - target/demo-0.0.1-SNAPSHOT.jar
      discard-paths: yes
    artifact2:
      files:
        - target/demo-0.0.1-SNAPSHOT.jar
      discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
